version: 2.1
orbs:
  codecov: codecov/codecov@3.2.4

jobs:
  checkout_code:
    docker:
      - image: cimg/node:20.11.0
    working_directory: ~/starter-fastify-js
    steps:
      - checkout
      - save_cache:
          key: repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}-1
          paths:
            - ~/starter-fastify-js

  install_dependencies:
    docker:
      - image: cimg/node:20.11.0
    working_directory: ~/starter-fastify-js
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}-1
      - run: npm ci --no-optional
      - save_cache:
          key: dependencies-{{ .Branch }}-{{ checksum "package.json" }}-1
          paths:
            - ~/starter-fastify-js/node_modules

  test:
    docker:
      - image: cimg/node:20.11.0
    working_directory: ~/starter-fastify-js
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}-1
      - restore_cache:
          keys:
            - dependencies-{{ .Branch }}-{{ checksum "package.json" }}-1
      - run:
          name: Run lint tests
          command: npm run lint
      - run:
          name: Run unit tests
          command: npm test
      - store_test_results:
          path: ~/starter-fastify-js/coverage/coverage-final.json
      - store_artifacts:
          path: ~/starter-fastify-js/coverage/coverage-final.json

  build:
    docker:
      - image: cimg/node:20.11.0
    working_directory: ~/starter-fastify-js
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}-1
      - restore_cache:
          keys:
            - dependencies-{{ .Branch }}-{{ checksum "package.json" }}-1
      - run:
          name: Build code
          command: npm run tsc

workflows:
  version: 2
  code-review:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - test:
          requires:
            - install_dependencies
          post-steps:
            - codecov/upload
      - build:
          requires:
            - test
